apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    name: myapp
    type: front-end
spec:
  template:
    metadata:
      name: app-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
  replicas: 6
  selector:
    matchLabels:
      app: myapp