apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-rs
  labels:
    app: apprs
    type: front-end
spec:
  template:
    metadata:
      name: app-pod
      labels:
        app: apprs
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 6
  selector:
    matchLabels:
      type: front-end